config/routes.rb
Lsi::Application.routes.draw do
  resources :users

  resources :places

  resources :projects

  resources :monedas

  resources :components

  resources :categories

  resources :mounts

  resources :packages

  resources :distributors

   root :to => 'components#index'

end

app/models/distributor.rb
class Distributor < ActiveRecord::Base
    has_many :components
end

app/controllers/distributors_controller.rb
class DistributorsController < ApplicationController
  # GET /distributors
  # GET /distributors.json
  def index
    @distributors = Distributor.find(:all , :order => :name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @distributors }
    end
  end

  # GET /distributors/1
  # GET /distributors/1.json
  def show
    @distributor = Distributor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @distributor }
    end
  end

  # GET /distributors/new
  # GET /distributors/new.json
  def new
    @distributor = Distributor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @distributor }
    end
  end

  # GET /distributors/1/edit
  def edit
    @distributor = Distributor.find(params[:id])
  end

  # POST /distributors
  # POST /distributors.json
  def create
    @distributor = Distributor.new(params[:distributor])

    respond_to do |format|
      if @distributor.save
        format.html { redirect_to @distributor, :notice => 'Distributor was successfully created.' }
        format.json { render :json => @distributor, :status => :created, :location => @distributor }
      else
        format.html { render :action => "new" }
        format.json { render :json => @distributor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /distributors/1
  # PUT /distributors/1.json
  def update
    @distributor = Distributor.find(params[:id])

    respond_to do |format|
      if @distributor.update_attributes(params[:distributor])
        format.html { redirect_to @distributor, :notice => 'Distributor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @distributor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /distributors/1
  # DELETE /distributors/1.json
  def destroy
    @distributor = Distributor.find(params[:id])
    @distributor.destroy

    respond_to do |format|
      format.html { redirect_to distributors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/distributors_helper.rb
module DistributorsHelper
end

app/views/distributors/_form.html.erb
<%= form_for(@distributor) do |f| %>
  <% if @distributor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@distributor.errors.count, "error") %> prohibited this distributor from being saved:</h2>

      <ul>
      <% @distributor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% f.label :name %>
    <%= t('distributor.name') %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit t('send')%>
  </div>
<% end %>

app/views/distributors/edit.html.erb
<h1><%= t('distributor.edit')%></h1>

<%= render 'form' %>

<%= link_to t('show'), @distributor %> |
<%= link_to t('back'), distributors_path %>

app/views/distributors/index.html.erb
<h1><%= t('distributor.list') %></h1>

<table>
  <tr>
    <th><%= t('distributor.name') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @distributors.each do |distributor| %>
  <tr>
    <td><%= distributor.name %></td>
    <td><%= link_to t('show'), distributor %></td>
    <td><%= link_to t('edit'), edit_distributor_path(distributor) %></td>
    <td><%= link_to t('delete'), distributor, :confirm => 'Estás seguro?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('distributor.new'), new_distributor_path %>

app/views/distributors/new.html.erb
<h1><%= t('distributor.new') %></h1>

<%= render 'form' %>

<%= link_to t('back'), distributors_path %>

app/views/distributors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('distributor.name') %></b>
  <%= @distributor.name %>
</p>


<%= link_to t('edit'), edit_distributor_path(@distributor) %> |
<%= link_to t('back'), distributors_path %>